### PR TITLE
Custom realtime support, better error descriptions + swift 5 support

### PR DESCRIPTION
**Pull request by OstapHolub**
This PR has a bunch of changes that is somehow connected with each other, so that's why it's in the same PR.

Changes:
- Errors now got description according to status code of response. 
- Authenticate method changed his return value to map instead of string to support cases when for auth call server push user object back with access token
- Custom realtime events support. Before feathers-swift library was limited up to 4 realtime events. Extended count of supported realtime updates by switching to String type instead of Enum. Client can listen whatever realtime update he wants.
- Removed Carthage copy scripts that was supposed to fix Apple Submission bug. Unfortunately, after Xcode update this script started to causing another issues, so I removed it. Don't worry, you still can archive the app that is using Feather installed via Carthage and submit it to the App Store successfully. I have checked this and application passed AppStore review, works ok.
- Deprecated Swift 3 support. Added support of Swift 5

Temporary commented Travis podspec job until I find the reason why it's failing on Travis, but is working on local machine.

@daffl I have ready branches with Swift 5 support for feathers-rest and feathers-socketio, but we need to get this merged first to have Swift 5 version for theirs Carthage dependencies test to be passed. Please, let me know what do you think about this PR, what can be done better and we can get all mobile feathers libraries migrated to newest Swift version. Thank you!

### CODE REVIEW

**Comment by OstapHolub** [comment]
@daffl is there a way to rerun last Travis build? I fixed all the test, but this one failed because Carthage just stuck on checkout stage.

**Comment by daffl** [comment]
I added you as a collaborator here as well so you should now see a "Restart Build" button when you go into Travis.

**Comment by OstapHolub** [comment]
@daffl ok, looks like all checks have passed, thank you!

**Comment by daffl** [comment]
👍 Feel free to merge.

**Comment by daffl** [comment]
Actually, just merged it but you are welcome to squash merge yourself as long as tests are passing :shipit:

**Pull request merged**
